<div>
    <input type="text" class="<?php echo $class; ?>" id="<?php echo $formId; ?><?php echo $field; ?>_cond" name="<?php echo $formId; ?><?php echo $field ?>_cond" placeholder="<?php echo $placeholder; ?>" value="<?php echo $this->e($valueInput) ?? ''; ?>">
    <input type="hidden" id="<?php echo $formId; ?><?php echo $field ?>" name="<?php echo $formId; ?><?php echo $field ?>" value="<?php echo $this->e($value); ?>">
</div>
